# Generated by Django 5.2 on 2025-04-14 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customerrequest_employee_companyaccount_companybank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybank',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companybank',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
