# Generated by Django 5.2 on 2025-04-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companybank_added_on_alter_companybank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='buy_price',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='sell_price',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medical_type',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='shelf_no',
        ),
        migrations.AddField(
            model_name='company',
            name='bill_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_bills/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pack',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='schedule_type',
            field=models.CharField(choices=[('yes', 'no')], default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='c_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='s_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='MedicineDetails',
        ),
    ]
