# Generated by Django 5.2 on 2025-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_companybank_company_delete_companyaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='source',
            field=models.CharField(choices=[('existing', 'existing'), ('company', 'company')], default='company', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='schedule_type',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50),
        ),
    ]
