# Generated by Django 5.2 on 2025-04-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicine_source_alter_medicine_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='schedule_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
