# Generated by Django 5.2 on 2025-04-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_medicine_company_alter_medicine_schedule_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='source',
        ),
    ]
