# Generated by Django 5.2 on 2025-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_medicine_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueMedicineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('schedule_type', models.CharField(max_length=50)),
                ('in_stock_total', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='in_stock_total',
        ),
    ]
