# Generated by Django 5.2 on 2025-04-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_uniquemedicinedetail_remove_medicine_in_stock_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueMedicineDetail',
            new_name='MedicineStock',
        ),
    ]
