# Generated by Django 5.2 on 2025-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_uniquemedicinedetail_medicinestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestock',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=10),
            preserve_default=False,
        ),
    ]
