# Generated by Django 5.2 on 2025-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_medicinestock_mrp_medicinestock_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='amt_aftr_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
