# Generated by Django 5.2 on 2025-04-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_medicine_amt_aftr_gst_medicine_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='c_gst',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='s_gst',
        ),
    ]
