# Generated by Django 5.2 on 2025-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_medicine_c_gst_remove_medicine_s_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='c_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='s_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
