# Generated by Django 5.2 on 2025-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_medicine_c_gst_medicine_s_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestock',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
