# Generated by Django 5.2 on 2025-04-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_medicinestock_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinestock',
            name='profit',
        ),
    ]
