# Generated by Django 5.2 on 2025-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_customerrequest_bill_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredit',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='record_type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Credit', 'Credit')], default='Delivery', max_length=100),
            preserve_default=False,
        ),
    ]
