# Generated by Django 5.2 on 2025-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_customercredit_delivered_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_contact', models.CharField(max_length=15)),
                ('medicine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_list', models.TextField(blank=True, null=True)),
                ('prescription', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
