# Generated by Django 5.2 on 2025-05-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_amount_customercredit_pending_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercredit',
            name='address',
        ),
    ]
