# Generated by Django 5.2 on 2025-05-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_customercredit_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredit',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=100, null=True),
        ),
    ]
