# Generated by Django 5.2 on 2025-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_customercredit_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercredit',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='customercredit',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='customercredit',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customercredit',
            name='record_type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Credit', 'Credit')], default='Credit', max_length=100),
        ),
    ]
