# Generated by Django 5.2 on 2025-05-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_customercredit_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditDetailsSuperate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customercredit')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
        ),
    ]
