# Generated by Django 5.2 on 2025-05-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customercreditdetailssuperate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreditdetailssuperate',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicinestock'),
        ),
    ]
