# Generated by Django 5.2 on 2025-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_medicine_schedule_type_alter_medicine_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
