# Generated by Django 5.2 on 2025-06-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_billdetails_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetails',
            name='total_price',
        ),
    ]
