# Generated by Django 5.2 on 2025-06-10 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_billdetails_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercreditdetails',
            name='medicine',
        ),
        migrations.AddField(
            model_name='customercreditdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customercreditdetails',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercreditdetails',
            name='medicines',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomerCreditPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], default='Cash', max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customercredit')),
            ],
        ),
    ]
