# Generated by Django 5.2 on 2025-06-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_customercreditdetails_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreditdetails',
            name='customer_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customercredit'),
        ),
        migrations.RemoveField(
            model_name='customercreditdetailssuperate',
            name='customer_credit',
        ),
        migrations.RemoveField(
            model_name='customercreditdetailssuperate',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='customercreditreact',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customercreditdetails',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='CustomerCreditConnect',
        ),
        migrations.DeleteModel(
            name='CustomerCreditDetailsSuperate',
        ),
        migrations.DeleteModel(
            name='CustomerCreditReact',
        ),
    ]
