# Generated by Django 5.2 on 2025-06-12 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_customercreditdetails_customer_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinestock',
            name='schedule_type',
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField()),
                ('alert_date', models.DateField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('medicine_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicinestock')),
            ],
        ),
    ]
