# Generated by Django 5.2 on 2025-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_medicinestock_schedule_type_lowstockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockalert',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
