# Generated by Django 5.2 on 2025-06-12 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_lowstockalert_agency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowstockalert',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='lowstockalert',
            name='medicine_stock',
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='medicine_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
