# Generated by Django 5.2 on 2025-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_lowstockalert_agency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pack', models.CharField(max_length=100)),
                ('c_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('s_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amt_aftr_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch_no', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('mfg_date', models.DateField()),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_in_strip', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
